spring.datasource.url=jdbc:postgresql://localhost:5433/strongs_db?characterEncoding=UTF-8
spring.datasource.username=postgres
spring.datasource.password=extraction
spring.jpa.hibernate.ddl-auto=
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

server.error.include-message=always
