version: '2'
services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/url
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8000:8080"
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: url
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-postgres
    ports:
      - "8050:5432"